services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: skyplanner-dynamodb
    ports:
      - "8000:8000"
    volumes:
      - ./volumes/dynamodb:/home/dynamodblocal/data
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"
    restart: unless-stopped